##
## EPITECH PROJECT, 2021
## makefile
## File description:
## task01
##

all:
	make -C ./antman
	make -C ./giantman

clean:
		make clean -C ./antman
		make clean -C ./giantman

fclean: clean
		make fclean -C ./antman
		make fclean -C ./giantman

re: fclean all
